namecoin/ncdns

.travis.yml
This is the version currently used by Tor's build system; grep https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitian/versions for `GO_VER`.
=> Travis CI: Add Go 1.8.3.

.travis.yml, .travis/script
Adds the following osarch builds to Travis CI:
* linux/arm64
* linux/ppc64
* linux/ppc64le
* windows/386
* windows/amd64
=> Travis CI: Added more osarch builds.

tlsrestrict_chromium/chromium.go, tlsrestrict_chromium/chromium_test.go, tlsrestrict_chromium/tlsrestrict_chromium_tool/main.go
Add tool to restrict built-in CA's from issuing certs for .bit domains in Chromium.
This tool is intended to be run at install time (and would presumably be executed by the NSIS script).  Note that this tool should not be run on a Chromium profile that is open in a running Chromium instance; doing so might cause profile corruption.
=> Key pin injection for Chromium

.travis/script
All the gometalinter linters that produce warnings with the current codebase are configured to not fail the Travis build, but their output will still be printed to Travis logs.  Other linters will fail the Travis build.
=> Travis CI: Run gometalinter.

.travis.yml
Whoops, needs to be under `global:` or it gets interpreted as a build
matrix. @JeremyRand
=> Fix Travis environment variables

tlsrestrict_chromium/chromium.go
=> tlsrestrict: Remove unnecessary type conversions.

.travis/script
Temporary kludge for getting `q` and `dns-prop279` binaries included in the releases until we replace the build system with RBM.
=> Build system: Build q and dns-prop279

.travis/script, backend/backend.go, certdehydrate/certdehydrate.go, certdehydrate/certdehydrate_test.go, certinject/certinject_misc.go, certinject/certinject_windows.go, certinject/cryptoapi_windows.go, certinject/file.go, generate_nmc_cert/main.go, ncdomain/convert.go, tlshook/tlshook.go, tlsrestrictchromium/chromium.go, tlsrestrictchromium/chromium_test.go, tlsrestrictchromium/tlsrestrict_chromium_tool/main.go, util/util.go, util/util_test.go
Based on recommendations from static analysis.
=> Apply "gofmt -s"

server/server.go
This should be a harmless change, and for some unknown reason it fixed an "unexpected end of JSON input" RPC error on my Windows 10 x86_32 VM.
=> Change default Namecoin RPC host from localhost to 127.0.0.1.

.travis/script
Should fix one of the Travis failures.
=> Travis: Disable "test" and "aligncheck" static analyzers in both critical and non-critical steps

ncdomain/convert.go
Fixes #59, as well as a different bug that broke the same functionality as #59.
=> Fix rehydrated TLSA records served over DNS

ncdumpzone/ncdumpzone.go, tlsoverridefirefox/firefox.go
This mode outputs a cert_override.txt file (based on TLSA records) that Firefox will accept.  This can be used to facilitate positive overrides in Firefox.  A future PR will automate the procedure of syncing with Firefox.
Note that it won't create the correct hostname or fingerprint until #60 is merged.
=> ncdumpzone: Add Firefox mode.

.travis.yml, x509/x509_splice.go
Depends on #64.  Should not be merged until The Tor Project has upgraded their RBM descriptor to Go 1.9 or higher.
=> Upgrade to Go 1.9.

generate_nmc_cert/falsehost.go, generate_nmc_cert/main.go
~~Not yet tested; feel free to review/test but do not merge.~~
Ready for review, I think it's mergeable.
=> generate_nmc_cert: rebase against Go 1.8.3 standard library.

.travis/script, certdehydrate/certdehydrate_test.go, certinject/certinject.go, certinject/certinject_notwindows.go, certinject/certinject_windows.go, main.go, ncdomain/convert.go, server/server.go, tlsrestrictchromium/chromium.go, tlsrestrictchromium/chromium_test.go, tlsrestrictchromium/tlsrestrict_chromium_tool/main.go
=> Travis: various static analysis fixes/improvements

.travis/script
The gochecknoglobals is newly added to gometalinter, and it's breaking the build right now.  We should disable it until we've evaluated whether the issues it flags are significant.
=> Travis: disable gochecknoglobals as critical.

.travis.yml, x509/install.sh, x509/x509_splice.go
Depends on #65 .  Should not be merged until The Tor Project has upgraded their RBM descriptor to Go 1.10 or higher.
=> Upgrade to Go 1.10.

.travis/script, backend/backend.go, server/server.go
This PR adds the ability to automatically re-apply name constraints whenever an NSS application such as Firefox is updated.  Depends on https://github.com/namecoin/tlsrestrictnss/pull/14 .
=> Support tlsrestrictnsssync

.travis/script
Both of them are broken due to upstream issues.  The upstream breakage should be possible to workaround in rbm when we get around to it, but that's probably not going to happen before the next ncdns release.
=> Disable q and dns-prop279 in Travis

backend/backend.go, server/server.go
The 1500ms timeout regularly gets hit when using Electrum-NMC over Tor, so being able to configure it seems like a good idea.
=> Make Namecoin RPC timeout configurable

generate_nmc_cert/parent.go
`parent.go` was accidentally not updated when `x509` moved to an external repo; this is breaking the Travis build.  This PR fixes that.
=> generate_nmc_cert: Use external x509 package in parent.go

.travis.yml, .travis/after_success, .travis/script, backend/backend.go, backend/backend_notls.go, backend/backend_tls.go, ncdomain/convert.go, ncdomain/convert_notls.go, ncdomain/convert_notls_test.go, ncdomain/convert_test.go, ncdomain/convert_tls.go, ncdomain/convert_tls_test.go, server/server.go, server/server_notls.go, server/server_tls.go, tlshook/tlshook.go, tlshook/tlshook_notls.go
This PR allows building ncdns without TLSA record support.  Doing so decreases the binary size and attack surface significantly.
=> Add no_namecoin_tls build tag

backend/backend.go, namecoin/namecoin.go, ncdt/ncdt.go, ncdumpzone/ncdumpzone.go, server/server.go, server/web.go, util/util.go, util/util_test.go
This PR adds the plumbing for stream isolation (from madns to namecoin, without passing the stream ID to namecoind), and stream-isolates the LRU cache.  A follow-up PR will pass the stream ID to namecoind; that's currently blocked on https://github.com/namecoin/ncdns/pull/103 .
Prerequisites:
=> Add stream isolation (except for namecoind)

ncdumpzone/ncdumpzone.go
Fixes https://github.com/namecoin/ncdns/issues/105
TODO:
=> Fix infinite loop in ncdumpzone with Namecoin Core 0.18.0+

.travis.yml
Fixes a build fail for Darwin targets.
=> Travis: Use old goxnet for Go 1.11.x and earlier

certdehydrate/certdehydrate_test.go
`CreateCertificate` now checks the resulting signature as of Go 1.16+.  This was confusing our unit test for invalid dehydrated certs, which was expecting to need to verify the cert after the cert was created.
=> certdehydrate: Fix unit test for Golang issue 40458

.cirrus.yml, README.md
This reverts https://github.com/namecoin/ncdns/pull/137 .
The bug that necessitated disabling ASLR/PIE was fixed in https://github.com/hlandau/service/releases/tag/v2.0.17 ; thus we can enable it again in ncdns.
Fixes https://github.com/namecoin/ncdns/issues/138
=> Re-enable ASLR/PIE on Windows

.cirrus.yml, .golangci.yml
Fixes a warning from gomoddirectives linter.
=> CI: Whitelist go.mod replace x509-compressed

server/web.go
Fixes warning from `ifshort` linter.
=> Web server: use short if syntax

.cirrus.yml, README.md
Fixes error:
go: cannot determine module path for source directory
/home/redfish/foo/ncdns (outside GOPATH, module path must be
specified)
Fixes #141
=> readme: specify module path in go mod init command

.cirrus.yml, .golangci.yml, util/util.go
Also disable `varnamelen` linter pending an upstream fix so that the Cirrus build stops failing.
=> Cirrus: Fix varnamelen linter warnings

.cirrus.yml
certinject no longer bundles `go.mod` in Git.
=> Cirrus: Fix certinject modules

.cirrus.yml
Works around Go modules fail.
See https://github.com/hlandau/dexlogconfig/issues/7
=> Cirrus: Use local clone of go-systemd
