namecoin/ncdns

tlsrestrict_chromium/tlsrestrict_chromium_tool/main.go

tlsrestrict: Check error return value of config.Parse

---

Makefile

H/t to @domob1812 for reporting the issue.

Build: Makefile: move repo from hlandau/ncdns to namecoin/ncdns.

---

README.md

Revisions loosely based on feedback from @domob1812, who had some trouble with the existing instructions.

Docs: Refactor build instructions.

---

.travis/script

Travis CI: Reduce Gox parallelism to 3

---

certdehydrate/certdehydrate.go

Based on recommendations from static analysis.

certdehydrate: Improve comments for exported functions.

---

README.md

Mention DNSSEC Trigger.

---

.travis/script
server/web.go

Based on recommendations from "gosimple" static analysis.  ~Depends on https://github.com/namecoin/ncdns/pull/46 .~

Web server: minor refactor of initTemplates

---

certdehydrate/certdehydrate.go

Based on recommendations from "gas" static analysis.  ~~Depends on #50.~~

certdehydrate: Add some additional error checking

---

.travis/script

Do not merge this PR until miekg/dns#655 is fixed.

Re-enable netbsd/arm builds

---

ncdumpzone/ncdumpzone.go
ncdumpzone/ncdumpzone/ncdumpzone.go

Also a few other minor refactorings of ncdumpzone.
Refs https://github.com/namecoin/ncdns/pull/80 .

ncdumpzone: Refactor into library and executable.

---

.travis/script

Depends on https://github.com/namecoin/ncdns/pull/54 and https://github.com/namecoin/ncdns/pull/77 .  Should be mergeable after those are merged, assuming Travis passes at that point.

Travis: enable goimports static analyzer as critical.

---

generate_nmc_cert/main.go
generate_nmc_cert/parent.go

This enables compatibility of generated certs with mozilla::pkix TLS clients such as Firefox (which don't allow end-entity trust anchors), and also decreases the size of the data stored in the blockchain.  Support for actually using the generated certs is out of scope for this PR; the relevant code for ncp11 is already written, and the relevant code for certinject shouldn't be difficult to write later.

generate_nmc_cert: Support name-constrained CA's

---

.travis.yml

Travis: use more Go versions with x509-signature-splice 

---

ncdumpzone/ncdumpzone.go
ncdumpzone/ncdumpzone/ncdumpzone.go
rrtourl/rrtourl.go

This PR is intended to facilitate YaCy crawl jobs.

ncdumpzone: Add mode for a URL list.

---

README.md

Fixes https://github.com/namecoin/ncdns/issues/109

Fix build instructions for external x509

---

.travis.yml
README.md
certdehydrate/certdehydrate.go
certdehydrate/certdehydrate_test.go
generate_nmc_cert/falsehost.go
generate_nmc_cert/main.go
generate_nmc_cert/parent.go
ncdomain/convert_tls.go

Thanks to Filippo Valsorda for the tip.

Use splicesign and standard x509

---

.cirrus.yml
README.md

Refs https://github.com/hlandau/service/issues/14

Disable ASLR/PIE on Windows

---

COPYING

Requested by Stuart Gathman for Fedora packaging.

Add COPYING file (GPLv3)

---

.cirrus.yml
.golangci.yml
README.md
testdata/move_to_gopath.bash

Requested by Stuart Gathman for Fedora packaging.

Cirrus: Also run unit tests on Fedora

---

.cirrus.yml
backend/backend.go
ncdomain/convert.go
server/web.go

Also fix all warnings reported by that linter.

Cirrus: Mark errcheck linter as mandatory

---

.cirrus.yml
namecoin/namecoin.go
ncdt/ncdt.go
ncdumpzone/ncdumpzone/ncdumpzone.go
server/server.go

The last outstanding patch was merged upstream.
Fixes https://github.com/namecoin/ncdns/issues/162

Switch to upstream btcd

---

.cirrus.yml

Refs https://github.com/namecoin/ncdns/issues/166

Cirrus: Mark dupword linter as non-mandatory

---

cmd/ncdumpzone/ncdumpzone.go

cmd/ncdumpzone: Sort imports

---

.cirrus.yml

Fixes the unit tests on Fedora.

Fix go-systemd version in certinject

---

ncdomain/convert.go

binary DNS record parsing (CBOR)

binary DNS record parsing (CBOR)
